package com.ryandens.delegation;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import javax.tools.DiagnosticCollector;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.StandardLocation;
import javax.tools.ToolProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/** Unit tests for the source generated by {@link AutoDelegateProcessor} */
final class AutoDelegateProcessorTest {

  private static final Pattern DELEGATING_METHOD_NAME =
      Pattern.compile("^  public ([^(]*)\\(", Pattern.MULTILINE);

  private static final String BASE =
      "package test;\n"
          + "public interface Base {\n"
          + "  void zeta();\n"
          + "  String alpha(int x);\n"
          + "  default void mu() {}\n"
          + "}\n";

  private static final String ORDERED =
      "package test;\n"
          + "public interface Ordered extends Base {\n"
          + "  void omega();\n"
          + "  void beta();\n"
          + "  int kappa(String s);\n"
          + "}\n";

  private static final String OTHER =
      "package test;\n"
          + "public interface Other {\n"
          + "  void yankee();\n"
          + "  void xray();\n"
          + "}\n";

  @TempDir Path generatedSources;

  /**
   * Verifies that delegating methods follow the declaration order of the delegation target, with
   * methods inherited from superinterfaces after those declared on the target itself
   */
  @Test
  void test_methods_generated_in_declaration_order() {
    // WHEN we auto-delegate to an interface that extends another interface
    final var generated =
        generate(
            "OrderedImpl",
            BASE,
            ORDERED,
            "package test;\n"
                + "@com.ryandens.delegation.AutoDelegate(Ordered.class)\n"
                + "abstract class OrderedImpl implements Ordered {}\n");

    // VERIFY the delegating methods appear in declaration order
    assertEquals(
        List.of("omega", "beta", "kappa", "zeta", "alpha", "mu"), delegatingMethodNames(generated));
  }

  /**
   * Verifies that with multiple delegation targets, the delegating methods for each target follow
   * the order in which the annotated type implements those targets, not the order of {@link
   * AutoDelegate#to()}
   */
  @Test
  void test_multiple_delegation_targets_generated_in_implements_order() {
    // WHEN we auto-delegate to multiple interfaces listed in a different order than they are
    // implemented
    final var generated =
        generate(
            "MultiImpl",
            BASE,
            ORDERED,
            OTHER,
            "package test;\n"
                + "@com.ryandens.delegation.AutoDelegate(to = {Ordered.class, Other.class})\n"
                + "abstract class MultiImpl implements Other, Ordered {}\n");

    // VERIFY the delegating methods are grouped by delegation target in implements order, each in
    // declaration order
    assertEquals(
        List.of("yankee", "xray", "omega", "beta", "kappa", "zeta", "alpha", "mu"),
        delegatingMethodNames(generated));
  }

  /**
   * Verifies that a method inherited from more than one superinterface is delegated to only once
   */
  @Test
  void test_method_inherited_from_multiple_superinterfaces_generated_once() {
    // WHEN we auto-delegate to an interface that inherits the same method from two superinterfaces
    final var generated =
        generate(
            "DiamondImpl",
            "package test;\npublic interface Left {\n  void close();\n}\n",
            "package test;\npublic interface Right {\n  void close();\n}\n",
            "package test;\npublic interface Both extends Left, Right {}\n",
            "package test;\n"
                + "@com.ryandens.delegation.AutoDelegate(Both.class)\n"
                + "abstract class DiamondImpl implements Both {}\n");

    // VERIFY the inherited method is delegated to exactly once
    assertEquals(List.of("close"), delegatingMethodNames(generated));
  }

  /** Verifies that the processor generates identical source for identical input */
  @Test
  void test_generated_source_is_reproducible() {
    // GIVEN the source generated by one compilation
    final var source =
        "package test;\n"
            + "@com.ryandens.delegation.AutoDelegate(to = {Other.class, Ordered.class})\n"
            + "abstract class MultiImpl implements Other, Ordered {}\n";
    final var first = generate("MultiImpl", BASE, ORDERED, OTHER, source);

    // WHEN we repeat the same compilation, each with fresh compiler state
    for (int i = 0; i < 20; i++) {
      // VERIFY the generated source is identical
      assertEquals(first, generate("MultiImpl", BASE, ORDERED, OTHER, source));
    }
  }

  /**
   * Runs {@link AutoDelegateProcessor} over the provided sources in package {@code test} and
   * returns the source generated for the annotated class with the provided simple name
   */
  private String generate(final String annotatedClassName, final String... sources) {
    final var compiler = ToolProvider.getSystemJavaCompiler();
    final var diagnostics = new DiagnosticCollector<JavaFileObject>();
    final var outputDirectory = generatedSources.resolve(String.valueOf(System.nanoTime()));
    try (var fileManager = compiler.getStandardFileManager(diagnostics, Locale.ROOT, null)) {
      Files.createDirectories(outputDirectory);
      fileManager.setLocationFromPaths(StandardLocation.SOURCE_OUTPUT, List.of(outputDirectory));
      final var compilationUnits = new ArrayList<JavaFileObject>();
      for (final String source : sources) {
        compilationUnits.add(inMemorySource(source));
      }
      final var task =
          compiler.getTask(
              null,
              fileManager,
              diagnostics,
              List.of("-proc:only", "-classpath", System.getProperty("java.class.path")),
              null,
              compilationUnits);
      task.setProcessors(List.of(new AutoDelegateProcessor()));
      assertTrue(task.call(), () -> diagnostics.getDiagnostics().toString());
      return Files.readString(
          outputDirectory.resolve("test").resolve("AutoDelegate_" + annotatedClassName + ".java"));
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  private static JavaFileObject inMemorySource(final String source) {
    final var matcher = Pattern.compile("(?:interface|class) (\\w+)").matcher(source);
    if (!matcher.find()) {
      throw new IllegalArgumentException("No type declared in source: " + source);
    }
    return new SimpleJavaFileObject(
        URI.create("string:///test/" + matcher.group(1) + ".java"), JavaFileObject.Kind.SOURCE) {
      @Override
      public CharSequence getCharContent(final boolean ignoreEncodingErrors) {
        return source;
      }
    };
  }

  private static List<String> delegatingMethodNames(final String generatedSource) {
    final var names = new ArrayList<String>();
    final var matcher = DELEGATING_METHOD_NAME.matcher(generatedSource);
    while (matcher.find()) {
      final var signature = matcher.group(1);
      names.add(signature.substring(signature.lastIndexOf(' ') + 1));
    }
    return names;
  }
}
