name: "Publish Sonar JSON to Pixee"
on:
  check_suite:
    types: [completed]

jobs:
  publish:
    name: "Publish Sonar JSON to Pixee"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Sonar JSON to Pixee"
        shell: bash

        run: |
          echo $(curl -v "https://sonarcloud.io/api/issues/search?componentKeys=ryandens_auto-delegate&pullRequest=24")
